INSERT INTO news (title, summary, content, category, featured) VALUES
('Mutirão de serviços reúne moradores neste sábado', 'Ação comunitária oferece orientação, saúde preventiva e atividades culturais.', 'A comunidade recebe neste sábado uma programação gratuita com serviços de orientação, cuidados preventivos e atividades para toda a família. A iniciativa reúne profissionais e voluntários locais.\n\nOs atendimentos serão realizados por ordem de chegada. A organização recomenda levar documento de identificação e comprovante de residência.', 'Jornalista', 1),
('Operação reforça segurança em áreas comerciais', 'Equipes ampliam rondas e ações educativas no centro.', 'A operação começou nesta semana e inclui rondas em horários de maior movimento. Comerciantes também recebem orientações sobre prevenção e canais de atendimento.', 'Polícia', 0),
('Nova clínica amplia atendimento preventivo', 'Espaço terá consultas agendadas e ações de conscientização.', 'A nova unidade inicia os atendimentos na próxima segunda-feira. Entre os serviços estão consultas, acompanhamento preventivo e palestras abertas à comunidade.', 'Médicos', 0),
('Bombeiros promovem campanha contra acidentes domésticos', 'Ação ensina cuidados com eletricidade, gás e primeiros socorros.', 'A campanha reúne recomendações práticas para reduzir riscos dentro de casa e informa quando acionar o atendimento de emergência.', 'Bombeiros', 0),
('Projeto aproxima o Judiciário da comunidade', 'Encontros explicam direitos e serviços disponíveis.', 'O projeto promove rodas de conversa em linguagem acessível, com foco em cidadania, direitos e formas de acesso aos serviços públicos.', 'Juiz', 0),
('Orientação jurídica gratuita atende moradores', 'Profissionais explicam procedimentos e encaminham demandas.', 'A atividade oferece informações jurídicas gerais e encaminhamento aos órgãos adequados. O atendimento não substitui consulta individual quando necessária.', 'Advogado', 0);

INSERT INTO professionals (category, name, age, role, address, hours, sections) VALUES
('Polícia', 'Marina Almeida', 38, 'Delegada de Polícia', NULL, 'Segunda a sexta, 8h às 17h', 'Lista de procurados|Pessoas desaparecidas|Lista de presos|Orientações de segurança'),
('Médicos', 'Dr. Rafael Santos', 44, 'Médico clínico geral', 'Av. Central, 250 — Centro', 'Segunda a sexta, 7h às 18h', 'Inauguração de consultório ou clínica|Serviços oferecidos|Entrevistas e artigos|Agenda de atendimento'),
('Bombeiros', 'Camila Ferreira', 35, 'Capitã do Corpo de Bombeiros', NULL, 'Plantão 24 horas', 'Incêndios combatidos|Desaparecimentos|Pessoas salvas|Prevenção e primeiros socorros'),
('Juiz', 'Dr. André Ribeiro', 49, 'Juiz de Direito', NULL, 'Segunda a sexta, 9h às 16h', 'Campanhas de conscientização|Ações e projetos do Poder Judiciário|Entrevistas sobre temas jurídicos'),
('Advogado', 'Paula Nascimento', 41, 'Advogada', 'Rua das Palmeiras, 90 — Sala 4', 'Segunda a sexta, 8h às 17h', 'Inauguração ou ampliação do escritório|Serviços oferecidos|Informações objetivas ao cidadão'),
('Jornalista', 'Carlos Peixoto', 35, 'Jornalista e editor responsável', NULL, 'Contato editorial: segunda a sexta, 9h às 18h', 'Reportagens e entrevistas exclusivas|Economia, política, educação, saúde, cultura e esportes|Investigações jornalísticas|Projetos jornalísticos e vídeos|Campanhas solidárias e utilidade pública|Reportagens, assessoria, fotografia e produção de conteúdo para empresas');

